#!/bin/env bash

if [ -f $CC ]; then
    printf "Could not find $CC.\n"
    exit 1
fi

IN=$1
OUT=$2

if ! command -v $CC &> /dev/null
then
    printf "Could not find $CC.\n"
    exit 1
fi

if [ -n $OUT ]; then
    printf "No output files specified"
fi

$CC $CFLAGS -S -o - $IN | grep -oE "#\w+ .*" > $OUT
